import { useMemo, useState } from 'react';
import { useLocation } from 'wouter';
import { Activity, AlertTriangle, ArrowRight, ArrowUpRight, Bell, BookOpen, Check, CheckCircle2, Clock3, FileCheck2, FilePlus2, FileText, Filter, Gauge, Link2, ListTodo, LoaderCircle, MessageSquareText, Plus, Search, Send, ShieldAlert, Sparkles, Target, TrendingUp, Upload, WandSparkles } from 'lucide-react';
import { Area, AreaChart, Bar, BarChart, CartesianGrid, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import type { DocumentRecord, Priority, Risk, Task } from '../data/model';
import { useOps } from '../context/OpsContext';
import { analyzeDocument, answerEnterpriseQuestion, detectRisks, explainDecision, extractTasks, generateInsights } from '../services/aiService';
import { EmptyState, Modal, PageHeading, Panel, PanelTitle, PriorityPill, SourceButton, StatusPill } from '../components/Common';

const people=['Alex Morgan','Priya Shah','Rahul Mehta','Sarah Wilson','Daniel Lee'];
const today=()=>new Date().toISOString().slice(0,10);
const formatDate=(value:string)=>new Date(`${value}T12:00:00`).toLocaleDateString('en-US',{month:'short',day:'numeric'});
const initials=(name:string)=>name.split(' ').map(p=>p[0]).join('');

export function LoginPage(){
  const [,setLocation]=useLocation();const [signIn,setSignIn]=useState(false);
  return <div className="login-page">
    <div className="login-brand"><span className="brand-mark"><Target size={19}/></span>OPSMIND <span>AI</span></div>
    <div className="login-content">
      <div className="login-copy"><div className="eyebrow"><span className="system-dot"/> INTELLIGENCE FOR OPERATIONS</div><h1>Knowledge should move work forward.</h1><p>Turn scattered enterprise information into clear actions, accountable decisions and confident execution.</p>
        <div className="login-proof"><span><Check size={14}/> Evidence-backed answers</span><span><Check size={14}/> Traceable decisions</span><span><Check size={14}/> Action-ready intelligence</span></div>
      </div>
      <div className="login-card"><div className="ai-mark"><Sparkles size={17}/></div><h2>Your operating picture, in one place.</h2><p>Explore a live demo workspace with realistic enterprise scenarios and local sample data.</p>
        <button className="button-primary login-continue" onClick={()=>setLocation('/dashboard')} data-testid="button-continue-demo">Continue with Demo <ArrowRight size={15}/></button>
        <button className="button-secondary login-signin" onClick={()=>setSignIn(true)} data-testid="button-signin">Sign in to OpsMind</button>
        <div className="login-foot"><span className="system-dot"/> Demo workspace · no account needed</div>
      </div>
    </div><div className="login-bottom"><span>OPSMIND AI</span><span>Enterprise intelligence that turns information into action.</span><span>© 2026 OpsMind</span></div>
    {signIn&&<Modal title="Sign in to OpsMind" subtitle="Authentication is not required for this prototype." onClose={()=>setSignIn(false)} footer={<button className="button-primary" onClick={()=>{setSignIn(false);setLocation('/dashboard');}} data-testid="button-signin-demo">Continue in demo</button>}><div className="notice"><Sparkles size={15}/>Choose the demo workspace to explore every feature. No credentials are collected.</div></Modal>}
  </div>;
}

export function DashboardPage(){
  const {data}=useOps();const [,setLocation]=useLocation();const [selected,setSelected]=useState<Risk|null>(null);
  const pending=data.tasks.filter(t=>t.status!=='Completed').length;
  const risky=data.tasks.filter(t=>t.status!=='Completed'&&t.riskScore>=70).length;
  const overdue=data.tasks.filter(t=>t.status==='Overdue').length;
  const stats=[{label:'Active projects',value:12,foot:'Across 6 departments',icon:LayersSymbol(),tone:'blue'},{label:'Pending actions',value:pending,foot:`${data.tasks.filter(t=>t.priority==='High'&&t.status!=='Completed').length} high priority`,icon:<ListTodo size={16}/>,tone:'violet'},{label:'At-risk tasks',value:risky,foot:'AI-flagged dependencies',icon:<ShieldAlert size={16}/>,tone:'amber'},{label:'Overdue tasks',value:overdue,foot:'Needs owner attention',icon:<Clock3 size={16}/>,tone:'rose'}];
  const alerts=data.risks.slice(0,3);
  return <div className="page">
    <PageHeading eyebrow="Friday, June 12, 2026 · Executive overview" title="Good morning, Alex" subtitle="Here’s what’s happening across your organization." actions={<button className="button-secondary" onClick={()=>setLocation('/insights')} data-testid="button-view-insights"><Activity size={14}/> View insights</button>}/>
    <div className="kpi-grid">{stats.map((s,i)=><Panel className="kpi-card" key={s.label}><div className="kpi-top"><span>{s.label}</span><span className={`kpi-icon tone-${s.tone}`}>{s.icon}</span></div><div className="kpi-value" data-testid={`kpi-value-${i}`}>{s.value}</div><div className="kpi-foot">{s.foot}</div></Panel>)}</div>
    <div className="dashboard-grid">
      <div style={{display:'grid',gap:16}}>
        <Panel className="panel-pad"><PanelTitle title="AI operational health" subtitle="A live view of delivery confidence across active work." action={<span className="trend-badge"><TrendingUp size={13}/> +4.2% this week</span>}/><div className="health-wrap"><div className="health-ring"><strong>87%</strong></div><div className="health-info"><strong>Operations are in a healthy position</strong><p>Most teams are on track. Vendor approval and campaign review need attention before they affect delivery.</p><div className="health-trend"><ArrowUpRight size={13}/> Improving over the last 7 days</div></div></div><div className="health-meter-label"><span>Delivery confidence</span><span>87 / 100</span></div><div className="health-meter"><div style={{width:'87%'}}/></div></Panel>
        <Panel className="panel-pad"><PanelTitle title="AI-detected priorities" subtitle="Recommended actions based on the latest project signals." action={<button className="button-ghost" onClick={()=>setLocation('/risks')} data-testid="button-all-risks">View all <ArrowRight size={13}/></button>}/><div style={{marginTop:12}}>{alerts.map(r=><div className="alert-row" key={r.id}><span className={`severity-mark severity-${r.severity.toLowerCase()}`}/><div className="alert-content"><div className="alert-title">{r.title}</div><div className="alert-meta">{r.project} · {r.affectedTasks} dependent tasks · {r.recommendation}</div></div><button className="alert-action" onClick={()=>setSelected(r)} data-testid={`button-risk-detail-${r.id}`}>Details</button></div>)}</div></Panel>
        <Panel className="panel-pad"><PanelTitle title="Priority work" subtitle="Actions most likely to influence delivery this week." action={<button className="button-ghost" onClick={()=>setLocation('/tasks')} data-testid="button-open-tasks">Open tasks <ArrowRight size={13}/></button>}/><div className="table-wrap" style={{marginTop:10}}><table className="data-table" style={{minWidth:600}}><thead><tr><th>Task</th><th>Owner</th><th>Due</th><th>Risk</th></tr></thead><tbody>{data.tasks.filter(t=>t.status!=='Completed'&&(t.riskScore>65||t.priority==='High')).slice(0,4).map(t=><tr key={t.id}><td><div className="task-title">{t.title}</div><div className="doc-sub">{t.project}</div></td><td>{t.owner}</td><td>{formatDate(t.deadline)}</td><td><span className={t.riskScore>70?'risk-number high':'risk-number'}>{t.riskScore}</span></td></tr>)}</tbody></table></div></Panel>
      </div>
      <div style={{display:'grid',alignContent:'start',gap:16}}>
        <Panel className="panel-pad"><PanelTitle title="AI agent activity" subtitle="Your operations layer is monitoring and acting." action={<span className="live-indicator"><span className="system-dot"/> Live</span>}/><div className="activity-list">{data.activities.slice(0,6).map((a,i)=><div className="activity-item" key={a.id}><div className="activity-glyph">{i===0?<Sparkles size={13}/>:i===1?<FileCheck2 size={13}/>:<Activity size={13}/>}</div><div><p>{a.label}</p><small>{a.time}</small></div></div>)}</div><button className="button-secondary full-width" style={{marginTop:8}} onClick={()=>setLocation('/actions')} data-testid="button-open-actions"><Sparkles size={13}/> Open AI actions</button></Panel>
        <Panel className="panel-pad"><PanelTitle title="Project pulse" subtitle="Featured delivery programs." action={<button className="button-ghost" onClick={()=>setLocation('/insights')} data-testid="button-project-pulse">Portfolio <ArrowRight size={13}/></button>}/><div className="project-pulse">{data.projects.slice(0,3).map(p=><div key={p.id} className="project-line"><div className="project-name"><span className={`project-status-dot ${p.status==='At risk'?'is-risk':''}`}/><div><strong>{p.name}</strong><small>{p.status}</small></div></div><div className="project-health"><strong>{p.health}%</strong><div className="mini-meter"><span style={{width:`${p.health}%`}}/></div></div></div>)}</div></Panel>
        <div className="insight-callout"><div className="eyebrow"><Sparkles size={13}/> EXECUTIVE SIGNAL</div><p>Vendor-related dependencies are behind <strong>35% of current project risk</strong>. One approval checkpoint can unblock three Atlas tasks.</p><button className="alert-action" onClick={()=>setLocation('/insights')} data-testid="button-explore-signal">Explore signal <ArrowRight size={12}/></button></div>
      </div>
    </div>
    {selected&&<RiskModal risk={selected} onClose={()=>setSelected(null)}/>}
  </div>;
}
function LayersSymbol(){return <Gauge size={16}/>}

function RiskModal({risk,onClose}:{risk:Risk;onClose:()=>void}){
  const [,setLocation]=useLocation();
  return <Modal title={risk.title} subtitle={`${risk.project} · ${risk.severity} severity`} onClose={onClose} footer={<><button className="button-secondary" onClick={onClose} data-testid="button-dismiss-risk">Dismiss</button><button className="button-primary" onClick={()=>{onClose();setLocation('/tasks');}} data-testid="button-risk-related-tasks">Review related tasks <ArrowRight size={13}/></button></>}>
    <div className="risk-metrics"><div><span>Probability</span><strong>{risk.probability}%</strong></div><div><span>Impact</span><strong>{risk.impact}</strong></div><div><span>Affected tasks</span><strong>{risk.affectedTasks}</strong></div></div>
    <div className="detail-block"><div className="detail-label"><ShieldAlert size={13}/> Risk assessment</div><p>{risk.detail}</p></div><div className="recommendation-box"><div className="detail-label"><Sparkles size={13}/> Recommended action</div><p>{risk.recommendation}</p></div>
  </Modal>;
}

export function WorkspacePage(){
  const {data,toast}=useOps();const [,setLocation]=useLocation();const [question,setQuestion]=useState('');const [answer,setAnswer]=useState<{answer:string;sources:string[]}|null>(null);const [loading,setLoading]=useState(false);
  const prompts=['What are the biggest operational risks this week?','Which projects are currently blocked?','Why was Vendor Alpha selected?','Show me overdue tasks.','Which deadlines are approaching?'];
  const ask=async(q=question)=>{if(!q.trim())return;setQuestion(q);setLoading(true);setAnswer(null);try{setAnswer(await answerEnterpriseQuestion(q,data.documents));}finally{setLoading(false);}};
  return <div className="page"><PageHeading eyebrow="Enterprise knowledge" title="Ask your organization" subtitle="Get answers from enterprise knowledge, documents and workflows." actions={<div className="ai-available"><span className="system-dot"/> Grounded in {data.documents.length} documents</div>}/>
    <div className="workspace-hero"><div className="workspace-head"><div className="ai-mark"><Sparkles size={17}/></div><div><h2 className="section-title">An operating answer, not another search</h2><div className="section-subtitle">Ask a question. OpsMind connects the evidence and points you to the source.</div></div></div><div className="question-box"><input value={question} onChange={e=>setQuestion(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')void ask();}} placeholder="Ask about a project, decision, deadline or risk..." data-testid="input-enterprise-question"/><button className="button-primary" onClick={()=>void ask()} disabled={loading} data-testid="button-ask">{loading?<LoaderCircle className="spin" size={14}/>:<Send size={14}/>} Ask OpsMind</button></div><div className="prompt-chips">{prompts.map(p=><button className="prompt-chip" key={p} onClick={()=>void ask(p)} data-testid={`prompt-${prompts.indexOf(p)}`}>{p}</button>)}</div></div>
    {loading&&<Panel className="answer-card loading-answer"><div className="answer-head"><div style={{display:'flex',gap:9,alignItems:'center'}}><div className="ai-mark" style={{width:28,height:28}}><Sparkles size={13}/></div><strong>Connecting operational evidence…</strong></div><LoaderCircle className="spin" size={16}/></div><div className="skeleton-line wide"/><div className="skeleton-line"/><div className="skeleton-line short"/></Panel>}
    {answer&&<Panel className="answer-card"><div className="answer-head"><div style={{display:'flex',gap:9,alignItems:'center'}}><div className="ai-mark" style={{width:29,height:29}}><Sparkles size={13}/></div><div><strong style={{fontSize:12,color:'#35435a'}}>OpsMind answer</strong><div className="section-subtitle">Grounded response · just now</div></div></div><span className="verified-tag"><CheckCircle2 size={12}/> Sources verified</span></div><p className="answer-copy">{answer.answer}</p><div className="source-head"><span className="eyebrow">Sources used</span><span className="section-subtitle">Open a source to inspect the record</span></div><div className="source-chips">{answer.sources.map((s)=><SourceButton key={s} label={s} onClick={()=>{setLocation('/documents');toast('Source located',`${s} is available in your document library.`,'info');}}/>)}</div><div className="answer-feedback"><span>Was this useful?</span><button onClick={()=>toast('Thanks for the feedback','Your response helps improve the demo experience.','info')} data-testid="button-answer-helpful">Helpful</button><button onClick={()=>toast('Feedback noted','We’ll use this to improve the answer.','info')} data-testid="button-answer-not-helpful">Not quite</button></div></Panel>}
    {!answer&&!loading&&<div className="workspace-lower"><Panel className="panel-pad"><PanelTitle title="Knowledge in context" subtitle="Recent records that shape today's operating picture."/><div className="knowledge-list">{data.documents.slice(0,4).map((d,i)=><div key={d.id} className="knowledge-row"><div className="knowledge-icon"><FileText size={15}/></div><div className="knowledge-copy"><strong>{d.title}</strong><small>{d.department} · Updated {formatDate(d.uploadedAt)}</small></div><span className="confidence">{i===0?'High match':'Relevant'}</span></div>)}</div></Panel><Panel className="panel-pad"><PanelTitle title="Popular questions" subtitle="Start with a question your team asks often."/><div className="popular-list">{prompts.slice(0,4).map(p=><button key={p} onClick={()=>void ask(p)} data-testid={`popular-${prompts.indexOf(p)}`}><MessageSquareText size={14}/><span>{p}</span><ArrowUpRight size={13}/></button>)}</div></Panel></div>}
  </div>;
}

export function DocumentsPage(){
  const {data,addDocument,toast}=useOps();const [search,setSearch]=useState('');const [department,setDepartment]=useState('All departments');const [type,setType]=useState('All types');const [selected,setSelected]=useState<DocumentRecord|null>(null);const [uploadOpen,setUploadOpen]=useState(false);
  const fileRef={current:null as HTMLInputElement|null};
  const filtered=data.documents.filter(d=>(!search||`${d.title} ${d.summary}`.toLowerCase().includes(search.toLowerCase()))&&(department==='All departments'||d.department===department)&&(type==='All types'||d.type===type));
  const upload=(file?:File)=>{const title=file?.name.replace(/\.[^.]+$/,'')||'New operations briefing';const doc:DocumentRecord={id:`doc-${Date.now()}`,title,type:file?.name.endsWith('.pdf')?'PDF report':'Text document',department:'Operations',uploadedAt:today(),status:'Analyzed',summary:`${title} has been added to the OpsMind knowledge library. The local analysis is ready for review; confirm the extracted actions and owners before sharing with your team.`,keyDecisions:['Record added to the shared operations workspace'],actions:['Review the imported record','Confirm accountable owner'],deadlines:['Review — June 19, 2026'],risks:['Owner confirmation is still required'],relatedProjects:['Project Atlas'],sources:[title]};addDocument(doc);setUploadOpen(false);setSelected(doc);toast('Document added',`${title} is now searchable in your library.`);};
  return <div className="page"><PageHeading eyebrow="Enterprise knowledge base" title="Documents" subtitle="A searchable source of truth for decisions, actions and deadlines." actions={<><button className="button-secondary" onClick={()=>{setDepartment('All departments');setType('All types');setSearch('');}} data-testid="button-clear-filters"><Filter size={14}/> Clear filters</button><button className="button-primary" onClick={()=>setUploadOpen(true)} data-testid="button-upload-document"><Upload size={14}/> Upload document</button></>}/>
    <div className="document-stat-row"><Panel className="doc-stat"><span>Documents</span><strong>{data.documents.length}</strong><small>Indexed in this workspace</small></Panel><Panel className="doc-stat"><span>Actions extracted</span><strong>{data.tasks.length}</strong><small>Linked to accountable owners</small></Panel><Panel className="doc-stat"><span>Risks detected</span><strong>{data.risks.length}</strong><small>Actively monitored by AI</small></Panel><Panel className="doc-stat"><span>Departments</span><strong>6</strong><small>Connected knowledge spaces</small></Panel></div>
    <Panel className="panel-pad" style={{marginTop:16}}><div className="toolbar"><div className="search-field-wrap"><Search size={15}/><input className="field" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search title or content..." data-testid="input-doc-search"/></div><select className="select-field" value={department} onChange={e=>setDepartment(e.target.value)} data-testid="select-department"><option>All departments</option>{['Engineering','Finance','Marketing','HR','Operations','Sales'].map(d=><option key={d}>{d}</option>)}</select><select className="select-field" value={type} onChange={e=>setType(e.target.value)} data-testid="select-doc-type"><option>All types</option>{Array.from(new Set(data.documents.map(d=>d.type))).map(d=><option key={d}>{d}</option>)}</select><div className="toolbar-spacer"/><span className="section-subtitle">{filtered.length} records</span></div>
    {filtered.length?<div className="document-grid">{filtered.map(d=><button className="document-card" key={d.id} onClick={()=>setSelected(d)} data-testid={`card-document-${d.id}`}><div className="document-card-top"><span className="document-icon"><FileText size={16}/></span><StatusPill status={d.status}/></div><h3>{d.title}</h3><p>{d.department} · {d.type}</p><div className="document-card-foot"><span>{formatDate(d.uploadedAt)}</span><span>{d.actions.length} actions · {d.risks.length} risks</span></div></button>)}</div>:<EmptyState title="No matching documents" detail="Try another title, department or document type." action={<button className="button-secondary" onClick={()=>{setSearch('');setDepartment('All departments');setType('All types');}} data-testid="button-reset-document-filters">Reset filters</button>}/>}</Panel>
    <input ref={el=>{fileRef.current=el;}} type="file" accept=".txt,.pdf,text/plain,application/pdf" hidden onChange={e=>{if(e.target.files?.[0])upload(e.target.files[0]);e.currentTarget.value='';}} data-testid="input-upload-file"/>
    {uploadOpen&&<Modal title="Add a document" subtitle="Import a TXT or PDF file into your local workspace." onClose={()=>setUploadOpen(false)} footer={<><button className="button-secondary" onClick={()=>setUploadOpen(false)} data-testid="button-cancel-upload">Cancel</button><button className="button-primary" onClick={()=>upload()} data-testid="button-simulate-upload"><FilePlus2 size={14}/> Add sample briefing</button></>}>
      <div className="upload-drop"><div className="empty-icon"><Upload size={19}/></div><strong>Drop a report into your knowledge base</strong><p>PDF and TXT files are supported. Files remain local to this demo.</p><button className="button-secondary" onClick={()=>fileRef.current?.click()} data-testid="button-choose-file">Choose file</button></div><div className="notice" style={{marginTop:13}}>Upload processing uses deterministic local analysis; no file is sent to an external service.</div>
    </Modal>}
    {selected&&<DocumentDetail document={selected} onClose={()=>setSelected(null)}/>}
  </div>;
}

function DocumentDetail({document:d,onClose}:{document:DocumentRecord;onClose:()=>void}){
  const [,setLocation]=useLocation();const {toast}=useOps();
  return <Modal title={d.title} subtitle={`${d.department} · ${d.type} · Added ${formatDate(d.uploadedAt)}`} onClose={onClose} footer={<><button className="button-secondary" onClick={onClose} data-testid="button-close-document">Close</button><button className="button-primary" onClick={()=>{onClose();setLocation('/actions');}} data-testid="button-analyze-document"><Sparkles size={14}/> Analyze with AI</button></>}>
    <div className="detail-section"><div className="detail-label"><BookOpen size={14}/> Document summary</div><p>{d.summary}</p></div>
    <div className="document-detail-grid"><div className="detail-section"><div className="detail-label"><CheckCircle2 size={14}/> Key decisions</div><ul>{d.keyDecisions.map(x=><li key={x}>{x}</li>)}</ul></div><div className="detail-section"><div className="detail-label"><ListTodo size={14}/> Extracted actions</div><ul>{d.actions.map(x=><li key={x}>{x}</li>)}</ul></div><div className="detail-section"><div className="detail-label"><Clock3 size={14}/> Deadlines</div><ul>{d.deadlines.map(x=><li key={x}>{x}</li>)}</ul></div><div className="detail-section"><div className="detail-label"><ShieldAlert size={14}/> Risks</div><ul>{d.risks.map(x=><li key={x}>{x}</li>)}</ul></div></div>
    <div className="detail-section"><div className="detail-label"><Target size={14}/> Related projects</div><div className="source-chips">{d.relatedProjects.map(p=><span key={p} className="source-chip">{p}</span>)}</div></div>
    <div className="detail-section"><div className="detail-label"><Link2 size={14}/> Sources & references</div><div className="source-chips">{d.sources.map(s=><SourceButton key={s} label={s} onClick={()=>toast('Source reference',`${s} is the originating evidence for this record.`,'info')}/>)}</div></div>
  </Modal>;
}

export function ActionsPage(){
  const {data,addTask,addRisk,addActivity,toast}=useOps();const [docId,setDocId]=useState(data.documents[0]?.id||'');const [result,setResult]=useState<null|{summary:string;actions:string[];risks:string[];citations:string[];tasks:Task[]}>(null);const [loading,setLoading]=useState(false);const [owner,setOwner]=useState('Priya Shah');const [created,setCreated]=useState(false);const [reminder,setReminder]=useState(false);
  const selected=data.documents.find(d=>d.id===docId)||data.documents[0];
  const analyze=async()=>{if(!selected)return;setLoading(true);setResult(null);setCreated(false);setReminder(false);try{const [analysis,tasks,risks]=await Promise.all([analyzeDocument(selected),extractTasks(selected),detectRisks(selected)]);setResult({...analysis,tasks});for(const r of risks){if(!r.title)continue;if(!data.risks.some(old=>old.title===r.title)){addRisk({id:`risk-${Date.now()}-${r.title}`,title:r.title,severity:r.severity||'Medium',probability:r.probability||58,impact:r.impact||'Medium',affectedTasks:r.affectedTasks||1,recommendation:r.recommendation||'Confirm an owner and review this dependency.',project:r.project||selected.relatedProjects[0]||'Project Atlas',detail:`Detected while analyzing ${selected.title}. Review related actions and confirm an accountable owner.`});}}addActivity(`Analyzed ${selected.title}; detected ${analysis.actions.length} actions and ${risks.length} risks`);}finally{setLoading(false);}};
  const createExtracted=()=>{const task=result?.tasks[0];if(!task)return;addTask({...task,id:`task-extracted-${Date.now()}`,owner});setCreated(true);addActivity(`Created task from ${selected.title}`);toast('Task created',`${task.title} has been added to Tasks.`);};
  return <div className="page"><PageHeading eyebrow="AI action engine" title="Turn documents into action" subtitle="Extract accountable work, deadlines and dependencies from enterprise knowledge." actions={<span className="ai-available"><span className="system-dot"/> Local AI engine ready</span>}/>
    <div className="actions-layout"><div><Panel className="panel-pad"><PanelTitle title="Choose a source document" subtitle="Select a library record or add a new one in Documents."/><div className="action-source-select"><select className="select-field" value={docId} onChange={e=>{setDocId(e.target.value);setResult(null);}} data-testid="select-action-document">{data.documents.map(d=><option value={d.id} key={d.id}>{d.title}</option>)}</select><button className="button-secondary" onClick={()=>void analyze()} disabled={loading||!selected} data-testid="button-run-analysis">{loading?<LoaderCircle className="spin" size={14}/>:<WandSparkles size={14}/>} {loading?'Analyzing…':'Analyze document'}</button></div>{selected&&<div className="selected-doc-summary"><FileText size={15}/><div><strong>{selected.title}</strong><small>{selected.department} · {selected.actions.length} noted actions · Added {formatDate(selected.uploadedAt)}</small></div><StatusPill status={selected.status}/></div>}</Panel>
      {loading&&<Panel className="analysis-card"><div className="analysis-working"><div className="analysis-orbit"><Sparkles size={21}/></div><h3>AI is analyzing enterprise data…</h3><p>Connecting document evidence to owners, due dates and project dependencies.</p><div className="analysis-skeleton"><span/><span/><span/></div></div></Panel>}
      {result&&<Panel className="analysis-card"><div className="analysis-complete"><div className="complete-icon"><CheckCircle2 size={17}/></div><div><div className="eyebrow" style={{color:'#33836c'}}>ANALYSIS COMPLETE</div><div className="section-subtitle">4 actions detected · {result.risks.length} risks · 1 dependency</div></div><span className="verified-tag"><Sparkles size={12}/> Local AI</span></div><div className="analysis-summary"><div className="detail-label">Executive summary</div><p>{result.summary}</p></div><div className="extracted-task"><div className="extracted-heading"><ListTodo size={15}/><strong>Extracted action</strong><PriorityPill priority={result.tasks[0]?.priority||'High'}/></div><h3>{result.tasks[0]?.title}</h3><div className="extract-fields"><div><small>Owner</small><select className="select-field" value={owner} onChange={e=>setOwner(e.target.value)} data-testid="select-extracted-owner">{people.map(p=><option key={p}>{p}</option>)}</select></div><div><small>Deadline</small><strong>{result.tasks[0]?.deadline==='2026-06-16'?'June 16, 2026':formatDate(result.tasks[0]?.deadline||today())}</strong></div><div><small>Priority</small><strong>High</strong></div><div><small>Dependency</small><strong>{result.tasks[0]?.dependency}</strong></div></div><div className="extract-actions"><button className="button-primary" onClick={createExtracted} disabled={created} data-testid="button-create-extracted-task">{created?<><Check size={14}/> Added to Tasks</>:<><Plus size={14}/> Create task</>}</button><button className="button-secondary" onClick={()=>toast('Owner assigned',`${owner} is selected as accountable owner.`)} data-testid="button-assign-owner">Assign owner</button><button className={`button-secondary ${reminder?'reminder-active':''}`} onClick={()=>{setReminder(true);toast('Reminder set','A local reminder is scheduled for the extracted deadline.');}} data-testid="button-set-reminder">{reminder?<Check size={13}/>:<Bell size={13}/>} {reminder?'Reminder set':'Set reminder'}</button></div></div><div className="risk-detected"><div className="detail-label"><ShieldAlert size={14}/> Detected risk</div>{result.risks.map((r,i)=><div key={i} className="risk-inline"><span className="severity-mark severity-high"/><span>{r}</span></div>)}</div><div className="source-chips">{result.citations.map(c=><span className="source-chip" key={c}><Link2 size={11}/>{c}</span>)}</div></Panel>}
      {!loading&&!result&&<Panel className="analysis-empty"><div className="empty-icon"><WandSparkles size={19}/></div><strong>Ready to connect the dots</strong><p>Run analysis to see extracted decisions, assigned actions and operational risks.</p><button className="button-primary" onClick={()=>void analyze()} data-testid="button-start-analysis"><Sparkles size={14}/> Analyze selected document</button></Panel>}</div>
      <div className="action-aside"><Panel className="panel-pad"><PanelTitle title="What the agent checks" subtitle="A document becomes a trackable workflow."/><div className="agent-checks">{[['01','Summarize','Understand the business context'],['02','Extract','Identify actions, owners and dates'],['03','Connect','Map project dependencies'],['04','Escalate','Surface risk before a deadline slips']].map(([n,t,d])=><div className="agent-check" key={n}><span>{n}</span><div><strong>{t}</strong><small>{d}</small></div><CheckCircle2 size={14}/></div>)}</div></Panel><Panel className="panel-pad"><PanelTitle title="Workflow impact" subtitle="Recent actions added to this workspace."/><div className="impact-metric"><strong>{data.tasks.length}</strong><span>tracked tasks</span></div><div className="impact-metric"><strong>{data.risks.length}</strong><span>monitored risks</span></div><div className="impact-footer"><ShieldAlert size={13}/> Every AI signal is traceable to a source.</div></Panel></div>
    </div>
  </div>;
}

export function TasksPage(){
  const {data,updateTask,addTask,addActivity,toast}=useOps();const [tab,setTab]=useState('All tasks');const [search,setSearch]=useState('');const [modal,setModal]=useState(false);const [followup,setFollowup]=useState(false);const [loadingFollow,setLoadingFollow]=useState(false);const [form,setForm]=useState({title:'',project:'Project Atlas',owner:'Alex Morgan',priority:'Medium' as Priority,deadline:'2026-06-19',dependency:''});
  const tabs=['All tasks','My tasks','At risk','Overdue','Completed'];
  const rows=data.tasks.filter(t=>tab==='My tasks'?t.owner==='Alex Morgan':tab==='At risk'?t.riskScore>=70&&t.status!=='Completed':tab==='Overdue'?t.status==='Overdue':tab==='Completed'?t.status==='Completed':true).filter(t=>`${t.title} ${t.owner} ${t.project}`.toLowerCase().includes(search.toLowerCase()));
  const submit=()=>{if(!form.title.trim()){toast('Task title required','Add a clear action name before saving.','info');return;}addTask({id:`task-${Date.now()}`,...form,status:'To do',riskScore:18});setModal(false);setForm({...form,title:''});toast('Task added','Your new task is ready to track.');};
  const runFollowup=async()=>{setLoadingFollow(true);await new Promise(r=>window.setTimeout(r,850));setLoadingFollow(false);setFollowup(true);addActivity('Follow-up agent notified 3 owners, created 1 escalation and scheduled 2 reminders');toast('AI follow-up completed','3 owners notified · 1 escalation created · 2 reminders scheduled.');};
  const select=(value:string,onChange:(v:string)=>void,options:string[],testId:string)=><select className="table-select" value={value} onChange={e=>onChange(e.target.value)} data-testid={testId}>{options.map(x=><option key={x}>{x}</option>)}</select>;
  return <div className="page"><PageHeading eyebrow="Execution management" title="Tasks" subtitle={`${data.tasks.filter(t=>t.status!=='Completed').length} active actions across your organization.`} actions={<><button className="button-secondary" onClick={()=>void runFollowup()} disabled={loadingFollow} data-testid="button-run-followup">{loadingFollow?<LoaderCircle className="spin" size={14}/>:<Sparkles size={14}/>} Run AI follow-up</button><button className="button-primary" onClick={()=>setModal(true)} data-testid="button-add-task"><Plus size={14}/> Add task</button></>}/>
    <div className="followup-panel"><div className="followup-mark"><Sparkles size={16}/></div><div className="followup-copy"><strong>AI Follow-Up Agent</strong><span>OpsMind monitors enterprise actions and follows up on pending work before a deadline slips.</span></div><div className="followup-examples"><span><b>Vendor API approval</b> · Reminder scheduled</span><span><b>Budget approval</b> · Escalation recommended</span></div>{followup&&<div className="followup-result"><CheckCircle2 size={15}/><span><strong>Follow-up completed</strong><small>3 owners notified · 1 escalation · 2 reminders</small></span></div>}</div>
    <Panel className="task-panel"><div className="task-panel-head"><div className="tabs">{tabs.map(t=><button className={`tab ${tab===t?'active':''}`} key={t} onClick={()=>setTab(t)} data-testid={`tab-${t.toLowerCase().replace(' ','-')}`}>{t}{t==='At risk'&&<span className="tab-count">{data.tasks.filter(x=>x.riskScore>=70&&x.status!=='Completed').length}</span>}</button>)}</div><div className="search-field-wrap task-search"><Search size={14}/><input className="field" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search actions..." data-testid="input-task-search"/></div></div>
      {rows.length?<div className="table-wrap"><table className="data-table task-table"><thead><tr><th>Action</th><th>Project</th><th>Owner</th><th>Priority</th><th>Deadline</th><th>Status</th><th>AI risk</th></tr></thead><tbody>{rows.map(t=><tr key={t.id} data-testid={`row-task-${t.id}`}><td><div className="task-title">{t.title}</div><div className="doc-sub">Dependency · {t.dependency||'None'}</div></td><td>{t.project}</td><td>{select(t.owner,v=>updateTask(t.id,{owner:v}),people,`select-owner-${t.id}`)}</td><td>{select(t.priority,v=>updateTask(t.id,{priority:v as Priority}),['High','Medium','Low'],`select-priority-${t.id}`)}</td><td><input className="date-select" type="date" value={t.deadline} onChange={e=>updateTask(t.id,{deadline:e.target.value,status:e.target.value<today()&&t.status!=='Completed'?'Overdue':t.status})} data-testid={`input-deadline-${t.id}`}/></td><td>{select(t.status,v=>{updateTask(t.id,{status:v as Task['status']});if(v==='Completed')toast('Task completed',t.title);},['To do','In progress','Blocked','Overdue','Completed'],`select-status-${t.id}`)}</td><td><span className={`risk-number ${t.riskScore>=70?'high':t.riskScore>=45?'medium':''}`}>{t.riskScore}<small>/100</small></span></td></tr>)}</tbody></table></div>:<EmptyState title="No tasks in this view" detail="Change your filters or create an action to get started." action={<button className="button-primary" onClick={()=>setModal(true)} data-testid="button-empty-add-task"><Plus size={13}/> Add a task</button>}/>}
      <div className="task-footer"><span>Showing {rows.length} of {data.tasks.length} actions</span><span><span className="system-dot"/> Synced locally</span></div>
    </Panel>
    {modal&&<Modal title="Create a task" subtitle="Turn an operational commitment into owned work." onClose={()=>setModal(false)} footer={<><button className="button-secondary" onClick={()=>setModal(false)} data-testid="button-cancel-task">Cancel</button><button className="button-primary" onClick={submit} data-testid="button-save-task"><Plus size={13}/> Create task</button></>}>
      <div className="form-grid"><div className="form-field" style={{gridColumn:'1 / -1'}}><label>Task name</label><input className="field" value={form.title} onChange={e=>setForm({...form,title:e.target.value})} placeholder="What needs to happen?" data-testid="input-new-task-title"/></div><div className="form-field"><label>Project</label><select className="select-field" value={form.project} onChange={e=>setForm({...form,project:e.target.value})} data-testid="select-new-task-project">{data.projects.slice(0,3).map(p=><option key={p.id}>{p.name}</option>)}</select></div><div className="form-field"><label>Owner</label><select className="select-field" value={form.owner} onChange={e=>setForm({...form,owner:e.target.value})} data-testid="select-new-task-owner">{people.map(p=><option key={p}>{p}</option>)}</select></div><div className="form-field"><label>Priority</label><select className="select-field" value={form.priority} onChange={e=>setForm({...form,priority:e.target.value as Priority})} data-testid="select-new-task-priority">{['High','Medium','Low'].map(p=><option key={p}>{p}</option>)}</select></div><div className="form-field"><label>Deadline</label><input type="date" className="field" value={form.deadline} onChange={e=>setForm({...form,deadline:e.target.value})} data-testid="input-new-task-deadline"/></div><div className="form-field" style={{gridColumn:'1 / -1'}}><label>Dependency (optional)</label><input className="field" value={form.dependency} onChange={e=>setForm({...form,dependency:e.target.value})} placeholder="What is this waiting on?" data-testid="input-new-task-dependency"/></div></div>
    </Modal>}
  </div>;
}

export function RisksPage(){
  const {data}=useOps();const [selected,setSelected]=useState<Risk|null>(null);const [filter,setFilter]=useState('All');
  const filtered=data.risks.filter(r=>filter==='All'||r.severity===filter);
  return <div className="page"><PageHeading eyebrow="Proactive operations" title="Risk center" subtitle="Find the dependencies most likely to interrupt delivery." actions={<div className="risk-filter">{['All','High','Medium','Low'].map(f=><button className={`filter-chip ${filter===f?'active':''}`} onClick={()=>setFilter(f)} key={f} data-testid={`filter-risk-${f.toLowerCase()}`}>{f}{f==='All'&&<span>{data.risks.length}</span>}</button>)}</div>}/>
    <div className="risk-summary"><Panel className="risk-summary-card"><div className="risk-summary-icon high"><ShieldAlert size={16}/></div><div><strong>{data.risks.filter(r=>r.severity==='High').length}</strong><span>High severity</span></div></Panel><Panel className="risk-summary-card"><div className="risk-summary-icon mid"><AlertTriangle size={16}/></div><div><strong>{data.risks.filter(r=>r.severity==='Medium').length}</strong><span>Needs attention</span></div></Panel><Panel className="risk-summary-card"><div className="risk-summary-icon calm"><CheckCircle2 size={16}/></div><div><strong>{data.risks.reduce((n,r)=>n+r.affectedTasks,0)}</strong><span>Linked actions</span></div></Panel><Panel className="risk-summary-card"><div className="risk-summary-icon ai"><Sparkles size={16}/></div><div><strong>24/7</strong><span>Continuous monitoring</span></div></Panel></div>
    <div className="risk-page-grid"><div className="risk-list-grid">{filtered.map(r=><button className={`risk-card sev-${r.severity.toLowerCase()}`} key={r.id} onClick={()=>setSelected(r)} data-testid={`card-risk-${r.id}`}><div className="risk-top"><span className={`risk-severity ${r.severity.toLowerCase()}`}>{r.severity} risk</span><span className="risk-score">{r.probability}%</span></div><h3 className="risk-title">{r.title}</h3><div className="risk-meta">{r.project} · {r.affectedTasks} affected tasks · {r.impact} impact</div><div className="risk-recommend"><Sparkles size={12}/><span>{r.recommendation}</span></div><div className="risk-card-foot"><span>AI confidence {Math.min(97,r.probability+8)}%</span><span>View assessment <ArrowRight size={12}/></span></div></button>)}{!filtered.length&&<EmptyState title="No risks at this severity" detail="Choose another severity to inspect monitored dependencies."/>}</div><Panel className="panel-pad risk-side"><PanelTitle title="Exposure by project" subtitle="Open risk assessments grouped by program."/><div className="exposure-list">{data.projects.slice(0,3).map(p=>{const c=data.risks.filter(r=>r.project===p.name).length;return <div className="exposure-row" key={p.id}><div><strong>{p.name}</strong><small>{c} open {c===1?'risk':'risks'}</small></div><span className={`exposure-grade ${c>2?'high':c>0?'medium':'low'}`}>{c>2?'Elevated':c>0?'Watch':'Clear'}</span></div>})}</div><div className="notice" style={{marginTop:18}}><Sparkles size={14}/> Each risk has a clear probability, impact and recommended next step.</div></Panel></div>
    {selected&&<RiskModal risk={selected} onClose={()=>setSelected(null)}/>}
  </div>;
}

export function DecisionsPage(){
  const {data,toast}=useOps();const [query,setQuery]=useState('');const [asked,setAsked]=useState(false);const [loading,setLoading]=useState(false);const [explanation,setExplanation]=useState('');
  const matches=data.decisions.filter(d=>!query||`${d.title} ${d.reason} ${d.evidence.join(' ')}`.toLowerCase().includes(query.toLowerCase()));
  const ask=async()=>{setLoading(true);setAsked(true);try{setExplanation(await explainDecision());}finally{setLoading(false);}};
  return <div className="page"><PageHeading eyebrow="Organizational memory" title="Decision memory" subtitle="Keep the reasoning behind consequential decisions connected to the work that follows." actions={<span className="ai-available"><BookOpen size={14}/> {data.decisions.length} recorded decisions</span>}/>
    <Panel className="decision-search-panel"><div className="decision-search-copy"><div className="ai-mark"><BookOpen size={16}/></div><div><h2 className="section-title">The reasoning matters as much as the result.</h2><p className="section-subtitle">Search decisions, compare evidence and follow the chain into execution.</p></div></div><div className="decision-query"><Search size={15}/><input value={query} onChange={e=>{setQuery(e.target.value);setAsked(false);}} onKeyDown={e=>{if(e.key==='Enter')void ask();}} placeholder="Why did we choose Vendor Alpha?" data-testid="input-decision-search"/><button className="button-primary" onClick={()=>void ask()} disabled={loading} data-testid="button-ask-decision">{loading?<LoaderCircle size={14} className="spin"/>:<Sparkles size={14}/>} Explain decision</button></div></Panel>
    {asked&&<Panel className="decision-answer"><div className="answer-head"><div className="detail-label"><Sparkles size={14}/> Decision chain explanation</div><span className="verified-tag"><CheckCircle2 size={12}/> Evidence linked</span></div>{loading?<div className="skeleton-line wide"/>:<><p>{explanation}</p><div className="decision-chain-steps"><span><FileText size={13}/> Evidence evaluated</span><ArrowRight size={13}/><span><CheckCircle2 size={13}/> Vendor Alpha selected</span><ArrowRight size={13}/><span><ListTodo size={13}/> Approval work tracked</span></div></>}</Panel>}
    <div className="decision-content-grid"><Panel className="panel-pad"><PanelTitle title="Decision timeline" subtitle="A traceable record of the choices shaping current operations."/><div className="decision-timeline">{matches.map(d=><article className="decision-card" key={d.id} data-testid={`decision-${d.id}`}><div className="decision-date">{formatDate(d.date)} · {d.decisionMakers.join(' + ')}</div><h3 className="decision-name">{d.title}</h3><p className="decision-reason">{d.reason}</p><div className="decision-evidence-label">Evidence considered</div><div className="source-chips">{d.evidence.map(s=><SourceButton key={s} label={s} onClick={()=>toast('Evidence linked',`${s} informed this decision.`,'info')}/>)}</div><div className="decision-linked"><span><Link2 size={12}/> Linked work</span>{d.relatedTasks.map(t=><button key={t} onClick={()=>toast('Related action',`${t} is tracked in Tasks.`,'info')} data-testid={`decision-task-${d.id}`}>{t}<ArrowUpRight size={11}/></button>)}</div></article>)}{!matches.length&&<EmptyState title="No decisions found" detail="Try searching a phrase, evidence source or decision owner."/>}</div></Panel>
      <div style={{display:'grid',gap:14,alignContent:'start'}}><Panel className="panel-pad"><PanelTitle title="Decision chain" subtitle="From evidence to accountable execution."/><div className="chain-vertical">{[['01','Source evidence','Reports, reviews and team notes'],['02','Decision rationale','Trade-offs and selected path'],['03','Named ownership','Teams and decision makers'],['04','Tracked follow-through','Tasks, dependencies and outcomes']].map(([n,t,s])=><div className="chain-step" key={n}><span>{n}</span><div><strong>{t}</strong><small>{s}</small></div></div>)}</div></Panel><div className="insight-callout"><div className="eyebrow"><BookOpen size={13}/> MEMORY PRINCIPLE</div><p>Decisions stay useful when their <strong>evidence, owners and next actions</strong> remain connected.</p></div></div></div>
  </div>;
}

export function InsightsPage(){
  const {data,toast,addInsights}=useOps();const [generated,setGenerated]=useState(false);const [loading,setLoading]=useState(false);
  const departmentData=[{name:'Eng.',open:11,high:6},{name:'Finance',open:5,high:3},{name:'Mktg.',open:6,high:2},{name:'HR',open:3,high:1},{name:'Ops',open:4,high:1},{name:'Sales',open:4,high:2}];
  const trendData=[{day:'Mon',health:80,risk:6},{day:'Tue',health:82,risk:6},{day:'Wed',health:81,risk:7},{day:'Thu',health:84,risk:6},{day:'Fri',health:83,risk:5},{day:'Mon',health:86,risk:5},{day:'Today',health:87,risk:5}];
  const run=async()=>{setLoading(true);const next=await generateInsights();addInsights(next);setGenerated(true);setLoading(false);toast('Management intelligence refreshed','New recommendations are ready to review.');};
  const workload=[{name:'Engineering',value:42},{name:'Finance',value:21},{name:'Marketing',value:17},{name:'Operations',value:12},{name:'Other',value:8}];
  const colors=['#586fc5','#8c78ce','#60a58d','#dfa94d','#a6afbd'];
  const insightCards=[{label:'OPERATIONAL TRENDS',icon:<TrendingUp size={15}/>,title:'Health is improving',body:'Portfolio delivery confidence has risen 4 points in the last week as owners closed cross-team dependencies.',to:'/dashboard'}, {label:'TOP BOTTLENECK',icon:<AlertTriangle size={15}/>,title:'Vendor approval is the hinge point',body:'The Atlas API approval gates three engineering actions. One Finance checkpoint can reduce the critical-path risk.',to:'/risks'}, {label:'UPCOMING DEADLINES',icon:<Clock3 size={15}/>,title:'Five checkpoints in 72 hours',body:'Budget sign-off, API approval and security review are the next portfolio milestones requiring an owner check.',to:'/tasks'}, {label:'RISK TREND',icon:<ShieldAlert size={15}/>,title:'Vendor risk remains concentrated',body:'Vendor-related dependencies account for 35% of active project risk exposure across the portfolio.',to:'/risks'}];
  const [,setLocation]=useLocation();
  return <div className="page"><PageHeading eyebrow="Management intelligence" title="Insights" subtitle="See the patterns, bottlenecks and deadlines shaping execution." actions={<button className="button-primary" onClick={()=>void run()} disabled={loading} data-testid="button-refresh-insights">{loading?<LoaderCircle size={14} className="spin"/>:<Sparkles size={14}/>} {loading?'Generating…':'Generate insights'}</button>}/>
    <div className="insight-card-grid">{insightCards.map((c,i)=><button className="insight-signal-card" key={c.title} onClick={()=>setLocation(c.to)} data-testid={`insight-card-${i}`}><div className="insight-signal-top"><span className="eyebrow">{c.icon}{c.label}</span><ArrowUpRight size={14}/></div><h3>{c.title}</h3><p>{c.body}</p><span className="insight-link">Explore evidence <ArrowRight size={12}/></span></button>)}</div>
    <div className="insights-chart-grid"><Panel className="panel-pad"><PanelTitle title="Operational trends" subtitle="Delivery confidence and monitored risks over the last seven workdays."/><div className="chart-box"><ResponsiveContainer width="100%" height="100%"><AreaChart data={trendData} margin={{top:10,right:8,left:-22,bottom:0}}><defs><linearGradient id="healthFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#5d73ca" stopOpacity={.2}/><stop offset="95%" stopColor="#5d73ca" stopOpacity={0}/></linearGradient></defs><CartesianGrid stroke="#edf0f5" vertical={false}/><XAxis dataKey="day" axisLine={false} tickLine={false} tick={{fontSize:10,fill:'#8993a4'}}/><YAxis domain={[70,100]} axisLine={false} tickLine={false} tick={{fontSize:10,fill:'#8993a4'}}/><Tooltip/><Area type="monotone" dataKey="health" name="Health" stroke="#596fc4" strokeWidth={2.5} fill="url(#healthFill)"/><Area type="monotone" dataKey="risk" name="Open risks" stroke="#dfa94d" strokeWidth={2} fill="transparent"/></AreaChart></ResponsiveContainer></div><div className="chart-legend"><span><i style={{background:'#596fc4'}}/> Operational health</span><span><i style={{background:'#dfa94d'}}/> Open risk signals</span></div></Panel>
    <Panel className="panel-pad"><PanelTitle title="Department workload" subtitle="Open work distribution by department."/><div className="workload-chart"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={workload} dataKey="value" innerRadius={56} outerRadius={77} paddingAngle={3} stroke="none">{workload.map((_,i)=><Cell key={i} fill={colors[i]}/>)}</Pie><Tooltip formatter={v=>`${v}%`}/></PieChart></ResponsiveContainer><div className="workload-center"><strong>28</strong><span>open tasks</span></div></div><div className="workload-legend">{workload.map((w,i)=><div key={w.name}><span><i style={{background:colors[i]}}/>{w.name}</span><b>{w.value}%</b></div>)}</div></Panel></div>
    <div className="insight-lower-grid"><Panel className="panel-pad"><PanelTitle title="Workload by department" subtitle="High-priority activity requiring an owner check."/><div style={{height:204,marginTop:12}}><ResponsiveContainer width="100%" height="100%"><BarChart data={departmentData} margin={{top:8,right:4,left:-22,bottom:0}}><CartesianGrid stroke="#edf0f5" vertical={false}/><XAxis dataKey="name" axisLine={false} tickLine={false} tick={{fontSize:10,fill:'#8993a4'}}/><YAxis axisLine={false} tickLine={false} tick={{fontSize:10,fill:'#8993a4'}}/><Tooltip/><Bar dataKey="open" name="Open work" fill="#7d8ed4" radius={[4,4,0,0]}/><Bar dataKey="high" name="High priority" fill="#d6a451" radius={[4,4,0,0]}/></BarChart></ResponsiveContainer></div></Panel><Panel className="panel-pad"><PanelTitle title="AI recommendations" subtitle="Specific next moves based on current signals."/><div className="recommendation-list">{data.insights.slice(0,4).map(i=><div className="recommendation-item" key={i.id}><div className="recommendation-icon"><Sparkles size={13}/></div><div><span>{i.category}</span><strong>{i.title}</strong><p>{i.description}</p></div></div>)}</div>{generated&&<div className="notice"><CheckCircle2 size={14}/> Latest intelligence generated locally just now.</div>}</Panel></div>
  </div>;
}

export function SettingsPage(){
  const {data,updatePreference,resetDemo,toast}=useOps();const [confirm,setConfirm]=useState(false);
  return <div className="page"><PageHeading eyebrow="Workspace administration" title="Settings" subtitle="Tune your demo workspace and local notification preferences."/>
    <div className="settings-layout"><div style={{display:'grid',gap:15}}><Panel className="panel-pad"><PanelTitle title="Workspace preferences" subtitle="Changes are saved on this device."/><div className="settings-row"><div><strong>Compact data tables</strong><p>Show more task and document rows in less space.</p></div><button className={`toggle ${data.preferences.compact?'on':''}`} role="switch" aria-checked={data.preferences.compact} onClick={()=>updatePreference('compact',!data.preferences.compact)} data-testid="toggle-compact"/></div><div className="settings-row"><div><strong>AI follow-up reminders</strong><p>Keep local reminder actions enabled across the workspace.</p></div><button className={`toggle ${data.preferences.reminders?'on':''}`} role="switch" aria-checked={data.preferences.reminders} onClick={()=>updatePreference('reminders',!data.preferences.reminders)} data-testid="toggle-reminders"/></div><div className="settings-row"><div><strong>Weekly executive digest</strong><p>Include a summary of risks, actions and delivery trends.</p></div><button className={`toggle ${data.preferences.weeklyDigest?'on':''}`} role="switch" aria-checked={data.preferences.weeklyDigest} onClick={()=>updatePreference('weeklyDigest',!data.preferences.weeklyDigest)} data-testid="toggle-digest"/></div></Panel><Panel className="panel-pad"><PanelTitle title="AI and data" subtitle="A private, deterministic demo environment."/><div className="settings-row"><div><strong>AI service mode</strong><p>Local deterministic intelligence · no external API calls.</p></div><span className="status-pill pill-done">Operational</span></div><div className="settings-row"><div><strong>Workspace records</strong><p>{data.documents.length} documents · {data.tasks.length} tasks · {data.risks.length} risks</p></div><span className="data-local-badge"><ShieldAlert size={13}/> Stored locally</span></div></Panel></div><Panel className="panel-pad reset-panel"><div className="reset-icon"><AlertTriangle size={17}/></div><h2 className="section-title">Reset demo data</h2><p>Restore the original OpsMind scenario, tasks, documents and settings. This will remove all changes made in this browser.</p><button className="button-danger" onClick={()=>setConfirm(true)} data-testid="button-reset-data">Restore original demo</button><div className="reset-note"><CheckCircle2 size={13}/> No backend or account data is affected.</div></Panel></div>
    {confirm&&<Modal title="Restore original demo data?" subtitle="This action cannot be undone." onClose={()=>setConfirm(false)} footer={<><button className="button-secondary" onClick={()=>setConfirm(false)} data-testid="button-cancel-reset">Keep my changes</button><button className="button-danger" onClick={()=>{resetDemo();setConfirm(false);}} data-testid="button-confirm-reset">Reset workspace</button></>}><div className="notice"><AlertTriangle size={14}/> All local tasks, uploaded documents, risk updates and preference changes will return to the original demo state.</div></Modal>}
  </div>;
}
